/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example.demo3;

import org.apache.commons.codec.digest.DigestUtils;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.dataformat.yaml.YAMLFactory;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        var om = new ObjectMapper(new YAMLFactory());
        System.out.println(DigestUtils.md5Hex("do re mi Abc 123"));
        System.out.println(new App().getGreeting());
    }
}
